services:
  postgres:
    image: postgres
    container_name: library-postgres
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypassword
    ports:
      - "5432:5432"
